name: "Release - PR Close"

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "# Release v${GITHUB_HEAD_REF##*/v} :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "PR #${{ github.event.number }} has been merged  " >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.pull_request.head.ref }} :arrow_right: ${{ github.event.pull_request.base.ref }}" >> $GITHUB_STEP_SUMMARY
        gh release create v${GITHUB_HEAD_REF##*/v} -t v${GITHUB_HEAD_REF##*/v}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
