# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Release - Publish"
on:
  release:
    types: [published]

jobs:
  sign:
    runs-on: windows-latest
    outputs:
      PKG_VERSION: ${{ steps.version-number.outputs.PKG_VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Sign code
        shell: pwsh
        run: |
          . ./build/Sign-Module.ps1
          $pswd = (ConvertTo-SecureString $env:PSWD -AsPlainText -Force)
          $result = Add-CodeSigning -PfxContent $env:CERT -CertificatePassword $pswd -SourceCodePath ./src
          '# Signing Details' | Add-Content $env:GITHUB_STEP_SUMMARY
          '```' | Add-Content $env:GITHUB_STEP_SUMMARY
          $result | ConvertTo-Json | Add-Content $env:GITHUB_STEP_SUMMARY
          '```' | Add-Content $env:GITHUB_STEP_SUMMARY
          $result
        env:
          PSWD: ${{ secrets.CODESIGN_PWD }}
          CERT: ${{ secrets.CODESIGN_PFX }}

      - name: Upload signed module
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ github.event.repository.name }}
          path: ./src/
          if-no-files-found: error
          retention-days: 1

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
         path: .
         recurse: true
         output: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Publish version
        id: version-number
        run: |
          $version = "${{ github.event.release.tag_name }}"
          "::set-output name=PKG_VERSION::$($version.Substring(1))"
        shell: pwsh

  test:
    strategy:
      matrix:
        platform: [windows, ubuntu, macos]

    runs-on: ${{ matrix.platform }}-latest
    needs: sign
    steps:
      - uses: actions/checkout@v3

      - name: Download signed code
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ github.event.repository.name }}
          path: ./src

      - name: Perform a Pester test
        shell: pwsh
        run: |
          Invoke-Pester ./tests -Passthru

      - name: Perform a Pester test (Desktop)
        if: ${{ matrix.platform == 'windows' }}
        shell: powershell
        run: |
          Invoke-Pester ./tests -Passthru

  publish:
    needs:
      - sign
      - test-windows
      - test-linux
      - test-macos
    runs-on: ubuntu-latest
    environment:
      name: PSGallery
      url: https://www.powershellgallery.com/packages/${{ github.event.repository.name }}/${{ needs.sign.outputs.PKG_VERSION }}
    steps:
      - name: Download module
        uses: actions/download-artifact@v3.0.0
        with:
         name: ${{ github.event.repository.name }}
         path: ./${{ github.event.repository.name }}

      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_API }}
        shell: pwsh
        run: Publish-Module -Path ./${{ github.event.repository.name }} -NuGetApiKey $env:NUGET_KEY -Verbose
